dist: trusty
language: rust
sudo: required
cache: cargo

rust:
  - stable
  - beta
  - nightly

os:
  - linux

env:
  global:
    - CRATE_NAME=ratelimit_meter
    - DEPLOY_VERSION=stable
    - RUN_CLIPPY=false
    - RUN_BENCHMARKS=false
    - RUSTFMT_VERSION=0.9.0

matrix:
  fast_finish: true # Don't wait for the clippy build - it takes forever /:
  include:
    - rust: nightly
      env: RUN_CLIPPY=true
    - rust: nightly
      env: RUN_BENCHMARKS=true
  allow_failures:
    - rust: nightly
      env: RUN_CLIPPY=true

before_script:
  - ./ci/before.sh

script:
  - ./ci/run-test.sh
  - ./ci/run-clippy.sh
  - ./ci/run-benchmark.sh

after_success:
  - ./ci/run-benchcmp.sh

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
