dist: trusty
language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

os:
  - linux

env:
  global:
    - CRATE_NAME=ratelimit_meter
    - DEPLOY_VERSION=stable
    - RUSTFMT_VERSION=v0.9.0

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      cargo install --list > /tmp/installed_crates;
      grep "^rustfmt $RUSTFMT_VERSION:" /tmp/installed_crates || cargo install rustfmt --vers $RUSTFMT_VERSION --force ;
    fi'
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo install clippy --force || touch .clippy_failure
      ;
    fi'


script:
  - cargo test
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      cargo fmt -v -- --write-mode diff
      ;
    fi'
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo bench
      ;
    fi'
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo clippy -- -D warnings;
    fi'
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo bench
    fi'

matrix:
  allow_failures:
    - nightly

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
