dist: trusty
language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

os:
  - linux

env:
  global:
    - CRATE_NAME=ratelimit_meter
    - DEPLOY_VERSION=stable

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo install clippy --force;
    fi'

script:
  - cargo test
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo clippy -- -D warnings;
    fi'

matrix:
  allow_failures:
    - nightly

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
