[package]
name = "ratelimit_meter"
version = "0.5.0-pre"
authors = ["Andreas Fuchs <asf@boinkor.net>"]
license = "MIT"
homepage = "https://github.com/antifuchs/ratelimit_meter"
repository = "https://github.com/antifuchs/ratelimit_meter.git"
readme = "README.md"
description = "A leaky-bucket-as-a-meter rate-limiting implementation in Rust"
documentation = "https://docs.rs/ratelimit_meter"

[badges]
travis-ci = { repository = "antifuchs/ratelimit_meter", branch = "master" }
maintenance = { status = "passively-maintained" }

[dependencies]
error-chain = "0.11.0-rc.2"
crossbeam = "0.3.0"